name: workout_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  google_fonts: ^6.3.1
  uuid: ^4.5.1
  collection: ^1.19.1
  haptic_feedback: ^0.5.1+1
  flutter_animate: ^4.5.2
  fl_chart: ^1.1.0
  intl: ^0.20.2
  csv: ^6.0.0
  share_plus: ^11.1.0
  lottie: ^3.3.2
  confetti: ^0.8.0
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  hive_generator: ^2.0.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/App_Icon.png"
  adaptive_icon_background: "#03092B"  # cyberpunk dark background
  remove_alpha_ios: true

flutter:
  uses-material-design: true
